module(load="imudp")
input(type="imudp" port="514")

module(load="ommysql")

*.* action(type="ommysql"
           server="mysql"
           port="3306"
           uid="tasklogger"
           pwd="tasklogger"
           db="tasklogger")
